export default {
	tableProps: () => ({
		url: utils.url(),
		method:'POST',
		headers: utils.headers(),
		schema: utils.schema(),
		bodyData:utils.bodyData(),
		dataKey: utils.dataKey(),
		rowActions: utils.rowActions(),
		rowSelectionAction: utils.rowSelectionAction(),
		colors: utils.colors(),
		pagination: utils.pagination(),
		showBorder: utils.showBorder(),
		actionColumn: utils.actionColumnConfig(),
		rowIndexColumn: utils.rowIndexColumn(),
		rowStyleRules: utils.rowStyleRules(),
		tableHeight: utils.tableHeight(),
		data: [],
		selectedRow: {},
		translations: {
			all: 'Hammasi',
			min: 'Min',
			max: 'Maks',
			filterPlaceholder: '{headerText} bo`yicha filter...',
			filterAriaLabel: '{headerText} bo`yicha filter',
			true: 'Rost',
			false: 'Yolg`on',
			dateFromAriaLabel: '{headerText} dan',
			dateToAriaLabel: '{headerText} gacha',
			numberMinAriaLabel: 'Minimal {headerText}',
			numberMaxAriaLabel: 'Maksimal {headerText}',
			goToFirstPage: 'Birinchi sahifaga o`tish',
			goToPreviousPage: 'Oldingi sahifaga o`tish',
			goToNextPage: 'Keyingi sahifaga o`tish',
			goToLastPage: 'Oxirgi sahifaga o`tish',
			error: 'Xato:',
			noData: 'Ma`lumotlar mavjud emas',
		}
	})
}